extern char _binary_MODE_TEXT_RESIDENTIAL_1_start;
extern char _binary_MODE_TEXT_RESIDENTIAL_2_start;
extern char _binary_MODE_TEXT_BUILD_HOSPITAL_start;
extern char _binary_MODE_TEXT_BUILD_POWER_GAS_start;
extern char _binary_MODE_TEXT_BUILD_POWER_SOLAR_start;
extern char _binary_MODE_TEXT_BUILD_RETAIL_start;
extern char _binary_MODE_TEXT_BUILD_ROAD_start;
extern char _binary_MODE_TEXT_DESTROY_start;

extern char _binary_VALUE_TEXT_EDUCATION_start;
extern char _binary_VALUE_TEXT_HEALTH_start;
extern char _binary_VALUE_TEXT_POLICE_start;
extern char _binary_VALUE_TEXT_POWER_start;
extern char _binary_VALUE_TEXT_SHOPPING_start;
extern char _binary_VALUE_TEXT_WASTE_start;

//extern char _binary__start;
